/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedEmptyPreviewRouteImport } from './routes/_authenticated/empty-preview'
import { Route as AuthenticatedDemoPreviewRouteImport } from './routes/_authenticated/demo-preview'
import { Route as AuthenticatedProfileMeRouteImport } from './routes/_authenticated/profile.me'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedProfileActivityRouteImport } from './routes/_authenticated/profile.activity'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedIntentsNewRouteImport } from './routes/_authenticated/intents.new'
import { Route as AuthenticatedIntentsIntentIdRouteImport } from './routes/_authenticated/intents.$intentId'
import { Route as AuthenticatedInboxThreadIdRouteImport } from './routes/_authenticated/inbox.$threadId'
import { Route as AuthenticatedIntentsIntentIdSubmissionsRouteImport } from './routes/_authenticated/intents.$intentId.submissions'
import { Route as AuthenticatedIntentsIntentIdRegisterRouteImport } from './routes/_authenticated/intents.$intentId.register'
import { Route as AuthenticatedIntentsIntentIdFormRouteImport } from './routes/_authenticated/intents.$intentId.form'
import { Route as AuthenticatedIntentsIntentIdFeedbackRouteImport } from './routes/_authenticated/intents.$intentId.feedback'
import { Route as AuthenticatedIntentsIntentIdEditRouteImport } from './routes/_authenticated/intents.$intentId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmptyPreviewRoute =
  AuthenticatedEmptyPreviewRouteImport.update({
    id: '/empty-preview',
    path: '/empty-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoPreviewRoute =
  AuthenticatedDemoPreviewRouteImport.update({
    id: '/demo-preview',
    path: '/demo-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileMeRoute = AuthenticatedProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileActivityRoute =
  AuthenticatedProfileActivityRouteImport.update({
    id: '/profile/activity',
    path: '/profile/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntentsNewRoute = AuthenticatedIntentsNewRouteImport.update({
  id: '/intents/new',
  path: '/intents/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntentsIntentIdRoute =
  AuthenticatedIntentsIntentIdRouteImport.update({
    id: '/intents/$intentId',
    path: '/intents/$intentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxThreadIdRoute =
  AuthenticatedInboxThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)
const AuthenticatedIntentsIntentIdSubmissionsRoute =
  AuthenticatedIntentsIntentIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedIntentsIntentIdRoute,
  } as any)
const AuthenticatedIntentsIntentIdRegisterRoute =
  AuthenticatedIntentsIntentIdRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedIntentsIntentIdRoute,
  } as any)
const AuthenticatedIntentsIntentIdFormRoute =
  AuthenticatedIntentsIntentIdFormRouteImport.update({
    id: '/form',
    path: '/form',
    getParentRoute: () => AuthenticatedIntentsIntentIdRoute,
  } as any)
const AuthenticatedIntentsIntentIdFeedbackRoute =
  AuthenticatedIntentsIntentIdFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedIntentsIntentIdRoute,
  } as any)
const AuthenticatedIntentsIntentIdEditRoute =
  AuthenticatedIntentsIntentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedIntentsIntentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo-preview': typeof AuthenticatedDemoPreviewRoute
  '/empty-preview': typeof AuthenticatedEmptyPreviewRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/inbox/$threadId': typeof AuthenticatedInboxThreadIdRoute
  '/intents/$intentId': typeof AuthenticatedIntentsIntentIdRouteWithChildren
  '/intents/new': typeof AuthenticatedIntentsNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/me': typeof AuthenticatedProfileMeRoute
  '/intents/$intentId/edit': typeof AuthenticatedIntentsIntentIdEditRoute
  '/intents/$intentId/feedback': typeof AuthenticatedIntentsIntentIdFeedbackRoute
  '/intents/$intentId/form': typeof AuthenticatedIntentsIntentIdFormRoute
  '/intents/$intentId/register': typeof AuthenticatedIntentsIntentIdRegisterRoute
  '/intents/$intentId/submissions': typeof AuthenticatedIntentsIntentIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo-preview': typeof AuthenticatedDemoPreviewRoute
  '/empty-preview': typeof AuthenticatedEmptyPreviewRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/inbox/$threadId': typeof AuthenticatedInboxThreadIdRoute
  '/intents/$intentId': typeof AuthenticatedIntentsIntentIdRouteWithChildren
  '/intents/new': typeof AuthenticatedIntentsNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/me': typeof AuthenticatedProfileMeRoute
  '/intents/$intentId/edit': typeof AuthenticatedIntentsIntentIdEditRoute
  '/intents/$intentId/feedback': typeof AuthenticatedIntentsIntentIdFeedbackRoute
  '/intents/$intentId/form': typeof AuthenticatedIntentsIntentIdFormRoute
  '/intents/$intentId/register': typeof AuthenticatedIntentsIntentIdRegisterRoute
  '/intents/$intentId/submissions': typeof AuthenticatedIntentsIntentIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/demo-preview': typeof AuthenticatedDemoPreviewRoute
  '/_authenticated/empty-preview': typeof AuthenticatedEmptyPreviewRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/inbox/$threadId': typeof AuthenticatedInboxThreadIdRoute
  '/_authenticated/intents/$intentId': typeof AuthenticatedIntentsIntentIdRouteWithChildren
  '/_authenticated/intents/new': typeof AuthenticatedIntentsNewRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/profile/activity': typeof AuthenticatedProfileActivityRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/me': typeof AuthenticatedProfileMeRoute
  '/_authenticated/intents/$intentId/edit': typeof AuthenticatedIntentsIntentIdEditRoute
  '/_authenticated/intents/$intentId/feedback': typeof AuthenticatedIntentsIntentIdFeedbackRoute
  '/_authenticated/intents/$intentId/form': typeof AuthenticatedIntentsIntentIdFormRoute
  '/_authenticated/intents/$intentId/register': typeof AuthenticatedIntentsIntentIdRegisterRoute
  '/_authenticated/intents/$intentId/submissions': typeof AuthenticatedIntentsIntentIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo-preview'
    | '/empty-preview'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/onboarding'
    | '/inbox/$threadId'
    | '/intents/$intentId'
    | '/intents/new'
    | '/profile/$userId'
    | '/profile/activity'
    | '/profile/edit'
    | '/profile/me'
    | '/intents/$intentId/edit'
    | '/intents/$intentId/feedback'
    | '/intents/$intentId/form'
    | '/intents/$intentId/register'
    | '/intents/$intentId/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo-preview'
    | '/empty-preview'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/onboarding'
    | '/inbox/$threadId'
    | '/intents/$intentId'
    | '/intents/new'
    | '/profile/$userId'
    | '/profile/activity'
    | '/profile/edit'
    | '/profile/me'
    | '/intents/$intentId/edit'
    | '/intents/$intentId/feedback'
    | '/intents/$intentId/form'
    | '/intents/$intentId/register'
    | '/intents/$intentId/submissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/demo-preview'
    | '/_authenticated/empty-preview'
    | '/_authenticated/explore'
    | '/_authenticated/home'
    | '/_authenticated/inbox'
    | '/_authenticated/onboarding'
    | '/_authenticated/inbox/$threadId'
    | '/_authenticated/intents/$intentId'
    | '/_authenticated/intents/new'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/profile/activity'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/me'
    | '/_authenticated/intents/$intentId/edit'
    | '/_authenticated/intents/$intentId/feedback'
    | '/_authenticated/intents/$intentId/form'
    | '/_authenticated/intents/$intentId/register'
    | '/_authenticated/intents/$intentId/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empty-preview': {
      id: '/_authenticated/empty-preview'
      path: '/empty-preview'
      fullPath: '/empty-preview'
      preLoaderRoute: typeof AuthenticatedEmptyPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo-preview': {
      id: '/_authenticated/demo-preview'
      path: '/demo-preview'
      fullPath: '/demo-preview'
      preLoaderRoute: typeof AuthenticatedDemoPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/me': {
      id: '/_authenticated/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof AuthenticatedProfileMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/activity': {
      id: '/_authenticated/profile/activity'
      path: '/profile/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof AuthenticatedProfileActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intents/new': {
      id: '/_authenticated/intents/new'
      path: '/intents/new'
      fullPath: '/intents/new'
      preLoaderRoute: typeof AuthenticatedIntentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intents/$intentId': {
      id: '/_authenticated/intents/$intentId'
      path: '/intents/$intentId'
      fullPath: '/intents/$intentId'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$threadId': {
      id: '/_authenticated/inbox/$threadId'
      path: '/$threadId'
      fullPath: '/inbox/$threadId'
      preLoaderRoute: typeof AuthenticatedInboxThreadIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/intents/$intentId/submissions': {
      id: '/_authenticated/intents/$intentId/submissions'
      path: '/submissions'
      fullPath: '/intents/$intentId/submissions'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedIntentsIntentIdRoute
    }
    '/_authenticated/intents/$intentId/register': {
      id: '/_authenticated/intents/$intentId/register'
      path: '/register'
      fullPath: '/intents/$intentId/register'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdRegisterRouteImport
      parentRoute: typeof AuthenticatedIntentsIntentIdRoute
    }
    '/_authenticated/intents/$intentId/form': {
      id: '/_authenticated/intents/$intentId/form'
      path: '/form'
      fullPath: '/intents/$intentId/form'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdFormRouteImport
      parentRoute: typeof AuthenticatedIntentsIntentIdRoute
    }
    '/_authenticated/intents/$intentId/feedback': {
      id: '/_authenticated/intents/$intentId/feedback'
      path: '/feedback'
      fullPath: '/intents/$intentId/feedback'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedIntentsIntentIdRoute
    }
    '/_authenticated/intents/$intentId/edit': {
      id: '/_authenticated/intents/$intentId/edit'
      path: '/edit'
      fullPath: '/intents/$intentId/edit'
      preLoaderRoute: typeof AuthenticatedIntentsIntentIdEditRouteImport
      parentRoute: typeof AuthenticatedIntentsIntentIdRoute
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxThreadIdRoute: typeof AuthenticatedInboxThreadIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxThreadIdRoute: AuthenticatedInboxThreadIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedIntentsIntentIdRouteChildren {
  AuthenticatedIntentsIntentIdEditRoute: typeof AuthenticatedIntentsIntentIdEditRoute
  AuthenticatedIntentsIntentIdFeedbackRoute: typeof AuthenticatedIntentsIntentIdFeedbackRoute
  AuthenticatedIntentsIntentIdFormRoute: typeof AuthenticatedIntentsIntentIdFormRoute
  AuthenticatedIntentsIntentIdRegisterRoute: typeof AuthenticatedIntentsIntentIdRegisterRoute
  AuthenticatedIntentsIntentIdSubmissionsRoute: typeof AuthenticatedIntentsIntentIdSubmissionsRoute
}

const AuthenticatedIntentsIntentIdRouteChildren: AuthenticatedIntentsIntentIdRouteChildren =
  {
    AuthenticatedIntentsIntentIdEditRoute:
      AuthenticatedIntentsIntentIdEditRoute,
    AuthenticatedIntentsIntentIdFeedbackRoute:
      AuthenticatedIntentsIntentIdFeedbackRoute,
    AuthenticatedIntentsIntentIdFormRoute:
      AuthenticatedIntentsIntentIdFormRoute,
    AuthenticatedIntentsIntentIdRegisterRoute:
      AuthenticatedIntentsIntentIdRegisterRoute,
    AuthenticatedIntentsIntentIdSubmissionsRoute:
      AuthenticatedIntentsIntentIdSubmissionsRoute,
  }

const AuthenticatedIntentsIntentIdRouteWithChildren =
  AuthenticatedIntentsIntentIdRoute._addFileChildren(
    AuthenticatedIntentsIntentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDemoPreviewRoute: typeof AuthenticatedDemoPreviewRoute
  AuthenticatedEmptyPreviewRoute: typeof AuthenticatedEmptyPreviewRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedIntentsIntentIdRoute: typeof AuthenticatedIntentsIntentIdRouteWithChildren
  AuthenticatedIntentsNewRoute: typeof AuthenticatedIntentsNewRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedProfileActivityRoute: typeof AuthenticatedProfileActivityRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileMeRoute: typeof AuthenticatedProfileMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDemoPreviewRoute: AuthenticatedDemoPreviewRoute,
  AuthenticatedEmptyPreviewRoute: AuthenticatedEmptyPreviewRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedIntentsIntentIdRoute:
    AuthenticatedIntentsIntentIdRouteWithChildren,
  AuthenticatedIntentsNewRoute: AuthenticatedIntentsNewRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedProfileActivityRoute: AuthenticatedProfileActivityRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileMeRoute: AuthenticatedProfileMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
